package nl.hu.inno.hulp.commons.exception;

public class NoExaminationFoundException extends RuntimeException {
    public NoExaminationFoundException(String message) {
        super(message);
    }
}
